// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: membership_query_messages.proto

package membershipQueryService

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Membership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID    string               `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GroupID   string               `protobuf:"bytes,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Status    int64                `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Role      int64                `protobuf:"varint,5,opt,name=Role,proto3" json:"Role,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *Membership) Reset() {
	*x = Membership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Membership) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Membership) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *Membership) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Membership) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *Membership) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Membership) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserMembership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GroupID      string               `protobuf:"bytes,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	UserID       string               `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MembershipID string               `protobuf:"bytes,4,opt,name=MembershipID,proto3" json:"MembershipID,omitempty"`
	Email        string               `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Username     string               `protobuf:"bytes,6,opt,name=Username,proto3" json:"Username,omitempty"`
	Status       int64                `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	Role         int64                `protobuf:"varint,8,opt,name=Role,proto3" json:"Role,omitempty"`
	CreatedAt    *timestamp.Timestamp `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt    *timestamp.Timestamp `protobuf:"bytes,10,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *UserMembership) Reset() {
	*x = UserMembership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMembership) ProtoMessage() {}

func (x *UserMembership) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMembership.ProtoReflect.Descriptor instead.
func (*UserMembership) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UserMembership) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserMembership) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *UserMembership) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserMembership) GetMembershipID() string {
	if x != nil {
		return x.MembershipID
	}
	return ""
}

func (x *UserMembership) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserMembership) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserMembership) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserMembership) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserMembership) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserMembership) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GroupMembership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID       string               `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GroupID      string               `protobuf:"bytes,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	MembershipID string               `protobuf:"bytes,4,opt,name=MembershipID,proto3" json:"MembershipID,omitempty"`
	Name         string               `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Description  string               `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	Status       int64                `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	Role         int64                `protobuf:"varint,8,opt,name=Role,proto3" json:"Role,omitempty"`
	Creator      bool                 `protobuf:"varint,9,opt,name=Creator,proto3" json:"Creator,omitempty"`
	CreatedAt    *timestamp.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt    *timestamp.Timestamp `protobuf:"bytes,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *GroupMembership) Reset() {
	*x = GroupMembership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembership) ProtoMessage() {}

func (x *GroupMembership) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembership.ProtoReflect.Descriptor instead.
func (*GroupMembership) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GroupMembership) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GroupMembership) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GroupMembership) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GroupMembership) GetMembershipID() string {
	if x != nil {
		return x.MembershipID
	}
	return ""
}

func (x *GroupMembership) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupMembership) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupMembership) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupMembership) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GroupMembership) GetCreator() bool {
	if x != nil {
		return x.Creator
	}
	return false
}

func (x *GroupMembership) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupMembership) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMembershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Membership      *Membership      `protobuf:"bytes,1,opt,name=Membership,proto3" json:"Membership,omitempty"`
	UserMembership  *UserMembership  `protobuf:"bytes,2,opt,name=UserMembership,proto3" json:"UserMembership,omitempty"`
	GroupMembership *GroupMembership `protobuf:"bytes,3,opt,name=GroupMembership,proto3" json:"GroupMembership,omitempty"`
}

func (x *CreateMembershipReq) Reset() {
	*x = CreateMembershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMembershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipReq) ProtoMessage() {}

func (x *CreateMembershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipReq.ProtoReflect.Descriptor instead.
func (*CreateMembershipReq) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMembershipReq) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

func (x *CreateMembershipReq) GetUserMembership() *UserMembership {
	if x != nil {
		return x.UserMembership
	}
	return nil
}

func (x *CreateMembershipReq) GetGroupMembership() *GroupMembership {
	if x != nil {
		return x.GroupMembership
	}
	return nil
}

type CreateMembershipRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CreateMembershipRes) Reset() {
	*x = CreateMembershipRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMembershipRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipRes) ProtoMessage() {}

func (x *CreateMembershipRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipRes.ProtoReflect.Descriptor instead.
func (*CreateMembershipRes) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMembershipRes) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type UpdateMembershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status int64  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Role   int64  `protobuf:"varint,5,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *UpdateMembershipReq) Reset() {
	*x = UpdateMembershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMembershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipReq) ProtoMessage() {}

func (x *UpdateMembershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipReq.ProtoReflect.Descriptor instead.
func (*UpdateMembershipReq) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMembershipReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateMembershipReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateMembershipReq) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type UpdateMembershipRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UpdateMembershipRes) Reset() {
	*x = UpdateMembershipRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMembershipRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipRes) ProtoMessage() {}

func (x *UpdateMembershipRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipRes.ProtoReflect.Descriptor instead.
func (*UpdateMembershipRes) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMembershipRes) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetMembershipByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetMembershipByIdReq) Reset() {
	*x = GetMembershipByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipByIdReq) ProtoMessage() {}

func (x *GetMembershipByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipByIdReq.ProtoReflect.Descriptor instead.
func (*GetMembershipByIdReq) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetMembershipByIdReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetMembershipByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Membership *Membership `protobuf:"bytes,1,opt,name=Membership,proto3" json:"Membership,omitempty"`
}

func (x *GetMembershipByIdRes) Reset() {
	*x = GetMembershipByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipByIdRes) ProtoMessage() {}

func (x *GetMembershipByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipByIdRes.ProtoReflect.Descriptor instead.
func (*GetMembershipByIdRes) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetMembershipByIdRes) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

type DeleteMembershipByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteMembershipByIdReq) Reset() {
	*x = DeleteMembershipByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMembershipByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipByIdReq) ProtoMessage() {}

func (x *DeleteMembershipByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipByIdReq.ProtoReflect.Descriptor instead.
func (*DeleteMembershipByIdReq) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMembershipByIdReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteMembershipByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMembershipByIdRes) Reset() {
	*x = DeleteMembershipByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMembershipByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipByIdRes) ProtoMessage() {}

func (x *DeleteMembershipByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipByIdRes.ProtoReflect.Descriptor instead.
func (*DeleteMembershipByIdRes) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{10}
}

type GetUserMembershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID string `protobuf:"bytes,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Page    int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size    int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *GetUserMembershipReq) Reset() {
	*x = GetUserMembershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMembershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMembershipReq) ProtoMessage() {}

func (x *GetUserMembershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMembershipReq.ProtoReflect.Descriptor instead.
func (*GetUserMembershipReq) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserMembershipReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GetUserMembershipReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserMembershipReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetUserMembershipRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount      int64             `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	TotalPages      int64             `protobuf:"varint,2,opt,name=TotalPages,proto3" json:"TotalPages,omitempty"`
	Page            int64             `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	Size            int64             `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	HasMore         bool              `protobuf:"varint,5,opt,name=HasMore,proto3" json:"HasMore,omitempty"`
	UserMemberships []*UserMembership `protobuf:"bytes,6,rep,name=UserMemberships,proto3" json:"UserMemberships,omitempty"`
}

func (x *GetUserMembershipRes) Reset() {
	*x = GetUserMembershipRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMembershipRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMembershipRes) ProtoMessage() {}

func (x *GetUserMembershipRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMembershipRes.ProtoReflect.Descriptor instead.
func (*GetUserMembershipRes) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserMembershipRes) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetUserMembershipRes) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetUserMembershipRes) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserMembershipRes) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetUserMembershipRes) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetUserMembershipRes) GetUserMemberships() []*UserMembership {
	if x != nil {
		return x.UserMemberships
	}
	return nil
}

type GetGroupMembershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Page   int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size   int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *GetGroupMembershipReq) Reset() {
	*x = GetGroupMembershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupMembershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembershipReq) ProtoMessage() {}

func (x *GetGroupMembershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembershipReq.ProtoReflect.Descriptor instead.
func (*GetGroupMembershipReq) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupMembershipReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetGroupMembershipReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupMembershipReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetGroupMembershipRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount       int64              `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	TotalPages       int64              `protobuf:"varint,2,opt,name=TotalPages,proto3" json:"TotalPages,omitempty"`
	Page             int64              `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	Size             int64              `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	HasMore          bool               `protobuf:"varint,5,opt,name=HasMore,proto3" json:"HasMore,omitempty"`
	GroupMemberships []*GroupMembership `protobuf:"bytes,6,rep,name=GroupMemberships,proto3" json:"GroupMemberships,omitempty"`
}

func (x *GetGroupMembershipRes) Reset() {
	*x = GetGroupMembershipRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_query_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupMembershipRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembershipRes) ProtoMessage() {}

func (x *GetGroupMembershipRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_query_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembershipRes.ProtoReflect.Descriptor instead.
func (*GetGroupMembershipRes) Descriptor() ([]byte, []int) {
	return file_membership_query_messages_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupMembershipRes) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetGroupMembershipRes) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetGroupMembershipRes) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupMembershipRes) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetGroupMembershipRes) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetGroupMembershipRes) GetGroupMemberships() []*GroupMembership {
	if x != nil {
		return x.GroupMemberships
	}
	return nil
}

var File_membership_query_messages_proto protoreflect.FileDescriptor

var file_membership_query_messages_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x01, 0x0a, 0x0a, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc8, 0x02, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x49, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xe7, 0x02, 0x0a, 0x0f, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x38, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0xfc, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x42, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x52, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x4e, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x51, 0x0a, 0x0f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x0f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x22,
	0x25, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x51, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x5a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x42, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0xea, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x48, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x12,
	0x50, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x52, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x73, 0x22, 0x57, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xee, 0x01, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x48, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x48,
	0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x73, 0x42, 0x1b, 0x5a, 0x19, 0x2e,
	0x2f, 0x3b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_membership_query_messages_proto_rawDescOnce sync.Once
	file_membership_query_messages_proto_rawDescData = file_membership_query_messages_proto_rawDesc
)

func file_membership_query_messages_proto_rawDescGZIP() []byte {
	file_membership_query_messages_proto_rawDescOnce.Do(func() {
		file_membership_query_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_membership_query_messages_proto_rawDescData)
	})
	return file_membership_query_messages_proto_rawDescData
}

var file_membership_query_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_membership_query_messages_proto_goTypes = []interface{}{
	(*Membership)(nil),              // 0: membershipQueryService.Membership
	(*UserMembership)(nil),          // 1: membershipQueryService.UserMembership
	(*GroupMembership)(nil),         // 2: membershipQueryService.GroupMembership
	(*CreateMembershipReq)(nil),     // 3: membershipQueryService.CreateMembershipReq
	(*CreateMembershipRes)(nil),     // 4: membershipQueryService.CreateMembershipRes
	(*UpdateMembershipReq)(nil),     // 5: membershipQueryService.UpdateMembershipReq
	(*UpdateMembershipRes)(nil),     // 6: membershipQueryService.UpdateMembershipRes
	(*GetMembershipByIdReq)(nil),    // 7: membershipQueryService.GetMembershipByIdReq
	(*GetMembershipByIdRes)(nil),    // 8: membershipQueryService.GetMembershipByIdRes
	(*DeleteMembershipByIdReq)(nil), // 9: membershipQueryService.DeleteMembershipByIdReq
	(*DeleteMembershipByIdRes)(nil), // 10: membershipQueryService.DeleteMembershipByIdRes
	(*GetUserMembershipReq)(nil),    // 11: membershipQueryService.GetUserMembershipReq
	(*GetUserMembershipRes)(nil),    // 12: membershipQueryService.GetUserMembershipRes
	(*GetGroupMembershipReq)(nil),   // 13: membershipQueryService.GetGroupMembershipReq
	(*GetGroupMembershipRes)(nil),   // 14: membershipQueryService.GetGroupMembershipRes
	(*timestamp.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_membership_query_messages_proto_depIdxs = []int32{
	15, // 0: membershipQueryService.Membership.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 1: membershipQueryService.Membership.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 2: membershipQueryService.UserMembership.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 3: membershipQueryService.UserMembership.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 4: membershipQueryService.GroupMembership.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 5: membershipQueryService.GroupMembership.UpdatedAt:type_name -> google.protobuf.Timestamp
	0,  // 6: membershipQueryService.CreateMembershipReq.Membership:type_name -> membershipQueryService.Membership
	1,  // 7: membershipQueryService.CreateMembershipReq.UserMembership:type_name -> membershipQueryService.UserMembership
	2,  // 8: membershipQueryService.CreateMembershipReq.GroupMembership:type_name -> membershipQueryService.GroupMembership
	0,  // 9: membershipQueryService.GetMembershipByIdRes.Membership:type_name -> membershipQueryService.Membership
	1,  // 10: membershipQueryService.GetUserMembershipRes.UserMemberships:type_name -> membershipQueryService.UserMembership
	2,  // 11: membershipQueryService.GetGroupMembershipRes.GroupMemberships:type_name -> membershipQueryService.GroupMembership
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_membership_query_messages_proto_init() }
func file_membership_query_messages_proto_init() {
	if File_membership_query_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_membership_query_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Membership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMembership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMembership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMembershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMembershipRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMembershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMembershipRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMembershipByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMembershipByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMembershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMembershipRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupMembershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_query_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupMembershipRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_membership_query_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_membership_query_messages_proto_goTypes,
		DependencyIndexes: file_membership_query_messages_proto_depIdxs,
		MessageInfos:      file_membership_query_messages_proto_msgTypes,
	}.Build()
	File_membership_query_messages_proto = out.File
	file_membership_query_messages_proto_rawDesc = nil
	file_membership_query_messages_proto_goTypes = nil
	file_membership_query_messages_proto_depIdxs = nil
}
