serviceName: query_service
grpc:
  port: :5003
  development: true
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3003
  pprof: :6003
  prometheusPath: /metrics
  prometheusPort: :8003
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: json
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: identity
  sslMode: false
kafka:
  brokers: [ "localhost:9092" ]
  groupID: command_service_consumer
  initTopics: true
kafkaTopics:
  userCreate:
    topicName: user_create
    partitions: 10
    replicationFactor: 1
  userUpdate:
    topicName: user_update
    partitions: 10
    replicationFactor: 1
  userCreated:
    topicName: user_created
    partitions: 10
    replicationFactor: 1
  userUpdated:
    topicName: user_updated
    partitions: 10
    replicationFactor: 1
  userDeleted:
    topicName: user_deleted
    partitions: 10
    replicationFactor: 1
  groupCreate:
    topicName: group_create
    partitions: 10
    replicationFactor: 1
  groupUpdate:
    topicName: group_update
    partitions: 10
    replicationFactor: 1
  groupCreated:
    topicName: group_created
    partitions: 10
    replicationFactor: 1
  groupUpdated:
    topicName: group_updated
    partitions: 10
    replicationFactor: 1
  groupDeleted:
    topicName: group_deleted
    partitions: 10
    replicationFactor: 1
  membershipCreate:
    topicName: membership_create
    partitions: 10
    replicationFactor: 1
  membershipUpdate:
    topicName: membership_update
    partitions: 10
    replicationFactor: 1
  membershipCreated:
    topicName: membership_created
    partitions: 10
    replicationFactor: 1
  membershipUpdated:
    topicName: membership_updated
    partitions: 10
    replicationFactor: 1
  membershipDeleted:
    topicName: membership_deleted
    partitions: 10
    replicationFactor: 1
  passwordUpdate:
    topicName: password_update
    partitions: 10
    replicationFactor: 1
  tokenBlacklist:
    topicName: token_blacklist
    partitions: 10
    replicationFactor: 1
  passwordUpdated:
    topicName: password_updated
    partitions: 10
    replicationFactor: 1
  tokenBlacklisted:
    topicName: token_blacklisted
    partitions: 10
    replicationFactor: 1
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
mongo:
  uri: "mongodb://localhost:27017"
  user: admin
  password: admin
  db: identity
mongoCollections:
  users: users
  groups: user_groups
  memberships: memberships
  userMemberships: user_memberships
  groupMemberships: group_memberships
  blacklist: blacklist
serviceSettings:
  redisUserPrefixKey: "query:user"
  redisGroupPrefixKey: "query:group"
  redisMembershipPrefixKey: "query:membership"
  redisUserMembershipPrefixKey: "query:userMembership"
  redisGroupMembershipPrefixKey: "query:groupMembership"
  redisTokenPrefixKey: "query:token"
  jwtSalt: "secretSALT"
jaeger:
  enable: true
  serviceName: query_service
  hostPort: "localhost:6831"
  logSpans: false