// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: membership_command_messages.proto

package membershipCommandService

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Membership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID    string               `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GroupID   string               `protobuf:"bytes,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Status    int64                `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Role      int64                `protobuf:"varint,5,opt,name=Role,proto3" json:"Role,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *Membership) Reset() {
	*x = Membership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_command_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_membership_command_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_membership_command_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Membership) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Membership) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *Membership) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Membership) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *Membership) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Membership) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMembershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GroupID string `protobuf:"bytes,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Status  int64  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Role    int64  `protobuf:"varint,5,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *CreateMembershipReq) Reset() {
	*x = CreateMembershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_command_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMembershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipReq) ProtoMessage() {}

func (x *CreateMembershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_command_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipReq.ProtoReflect.Descriptor instead.
func (*CreateMembershipReq) Descriptor() ([]byte, []int) {
	return file_membership_command_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMembershipReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateMembershipReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateMembershipReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *CreateMembershipReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateMembershipReq) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type CreateMembershipRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CreateMembershipRes) Reset() {
	*x = CreateMembershipRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_command_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMembershipRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipRes) ProtoMessage() {}

func (x *CreateMembershipRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_command_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipRes.ProtoReflect.Descriptor instead.
func (*CreateMembershipRes) Descriptor() ([]byte, []int) {
	return file_membership_command_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMembershipRes) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type UpdateMembershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status int64  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Role   int64  `protobuf:"varint,5,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *UpdateMembershipReq) Reset() {
	*x = UpdateMembershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_command_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMembershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipReq) ProtoMessage() {}

func (x *UpdateMembershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_command_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipReq.ProtoReflect.Descriptor instead.
func (*UpdateMembershipReq) Descriptor() ([]byte, []int) {
	return file_membership_command_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMembershipReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateMembershipReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateMembershipReq) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type UpdateMembershipRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMembershipRes) Reset() {
	*x = UpdateMembershipRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_command_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMembershipRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipRes) ProtoMessage() {}

func (x *UpdateMembershipRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_command_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipRes.ProtoReflect.Descriptor instead.
func (*UpdateMembershipRes) Descriptor() ([]byte, []int) {
	return file_membership_command_messages_proto_rawDescGZIP(), []int{4}
}

type GetMembershipByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetMembershipByIdReq) Reset() {
	*x = GetMembershipByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_command_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipByIdReq) ProtoMessage() {}

func (x *GetMembershipByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_membership_command_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipByIdReq.ProtoReflect.Descriptor instead.
func (*GetMembershipByIdReq) Descriptor() ([]byte, []int) {
	return file_membership_command_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetMembershipByIdReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetMembershipByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Membership *Membership `protobuf:"bytes,1,opt,name=Membership,proto3" json:"Membership,omitempty"`
}

func (x *GetMembershipByIdRes) Reset() {
	*x = GetMembershipByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_command_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipByIdRes) ProtoMessage() {}

func (x *GetMembershipByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_membership_command_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipByIdRes.ProtoReflect.Descriptor instead.
func (*GetMembershipByIdRes) Descriptor() ([]byte, []int) {
	return file_membership_command_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetMembershipByIdRes) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

var File_membership_command_messages_proto protoreflect.FileDescriptor

var file_membership_command_messages_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee,
	0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x83, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x51, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22,
	0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x5c,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x52, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x1d, 0x5a, 0x1b,
	0x2e, 0x2f, 0x3b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_membership_command_messages_proto_rawDescOnce sync.Once
	file_membership_command_messages_proto_rawDescData = file_membership_command_messages_proto_rawDesc
)

func file_membership_command_messages_proto_rawDescGZIP() []byte {
	file_membership_command_messages_proto_rawDescOnce.Do(func() {
		file_membership_command_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_membership_command_messages_proto_rawDescData)
	})
	return file_membership_command_messages_proto_rawDescData
}

var file_membership_command_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_membership_command_messages_proto_goTypes = []interface{}{
	(*Membership)(nil),           // 0: membershipCommandService.Membership
	(*CreateMembershipReq)(nil),  // 1: membershipCommandService.CreateMembershipReq
	(*CreateMembershipRes)(nil),  // 2: membershipCommandService.CreateMembershipRes
	(*UpdateMembershipReq)(nil),  // 3: membershipCommandService.UpdateMembershipReq
	(*UpdateMembershipRes)(nil),  // 4: membershipCommandService.UpdateMembershipRes
	(*GetMembershipByIdReq)(nil), // 5: membershipCommandService.GetMembershipByIdReq
	(*GetMembershipByIdRes)(nil), // 6: membershipCommandService.GetMembershipByIdRes
	(*timestamp.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_membership_command_messages_proto_depIdxs = []int32{
	7, // 0: membershipCommandService.Membership.CreatedAt:type_name -> google.protobuf.Timestamp
	7, // 1: membershipCommandService.Membership.UpdatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: membershipCommandService.GetMembershipByIdRes.Membership:type_name -> membershipCommandService.Membership
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_membership_command_messages_proto_init() }
func file_membership_command_messages_proto_init() {
	if File_membership_command_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_membership_command_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Membership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_command_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMembershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_command_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMembershipRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_command_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMembershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_command_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMembershipRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_command_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_command_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_membership_command_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_membership_command_messages_proto_goTypes,
		DependencyIndexes: file_membership_command_messages_proto_depIdxs,
		MessageInfos:      file_membership_command_messages_proto_msgTypes,
	}.Build()
	File_membership_command_messages_proto = out.File
	file_membership_command_messages_proto_rawDesc = nil
	file_membership_command_messages_proto_goTypes = nil
	file_membership_command_messages_proto_depIdxs = nil
}
