DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_groups CASCADE;
DROP TABLE IF EXISTS memberships CASCADE;
DROP TABLE IF EXISTS blacklists CASCADE;
DROP EXTENSION IF EXISTS citext CASCADE;